name: Metrics
on:
  # 每天自动更新一次
  schedule: [{cron: "0 0 * * *"}]
  # 可手动运行
  workflow_dispatch:
  # 当推送到 main 分支时运行（可选）
  push: {branches: ["main", "master"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: NNNietzsche
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Tokyo
          plugins_activity: yes
          plugins_languages: yes
          plugins_achievements: yes
